### ISSUE TITLE
Does it support live migration of pods of other workloads?

### ISSUE THREAD

**Issue by googs1025** [Jiaxuan-C/migration-operator#2]
As the title indicates, in general scenarios, other workloads are used to encapsulate the pod object so that it has more operation and maintenance functions. Does it support live migration of other workloads? In addition, what modifications are made to kubelet? Can you use a fork kubernetes repository instead of uploading the source code directly, so that we can also know what has been modified from the commit?

**Comment by Jiaxuan-C** [comment]
Live migration is possible for most workloads. However, for those Pods that already have a TCP connection established, the migration will disconnect their TCP connection, specifically because I used the parameter `--tcp-establish-closed` in the invocation of criu. that's because the Pod IPs are modified during the migration process, and I've not handled this part for now. But I think we can modify the Kubelet source code or sth. to allow Pods with the same IP to exist during the migration process, and then do some work on the CNI to restore the tcp connection.

Also, I really should organize my repositories, but I've been a bit too busy lately haha, I'll think about it later. If you want to check out the source code at the moment you can download my k8s source code for now and then check out the Kubelet section of the source code, most the locations I've modified are marked `TODO` by me.

Thank you for your advice.

**Comment by googs1025** [comment]
我会再研究研究，正好最近内部有类似迁移的需求, thanks!
